"""baseline

Revision ID: 599c526c6081
Revises: 
Create Date: 2026-07-27 18:51:21.441432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599c526c6081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_svc'
    )
    op.create_index(op.f('ix_auth_svc_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='auth_svc')
    op.create_index(op.f('ix_auth_svc_api_keys_user_id'), 'api_keys', ['user_id'], unique=False, schema='auth_svc')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_svc'
    )
    op.create_index(op.f('ix_auth_svc_users_email'), 'users', ['email'], unique=True, schema='auth_svc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_svc_users_email'), table_name='users', schema='auth_svc')
    op.drop_table('users', schema='auth_svc')
    op.drop_index(op.f('ix_auth_svc_api_keys_user_id'), table_name='api_keys', schema='auth_svc')
    op.drop_index(op.f('ix_auth_svc_api_keys_key_hash'), table_name='api_keys', schema='auth_svc')
    op.drop_table('api_keys', schema='auth_svc')
    # ### end Alembic commands ###
